### ISSUE TITLE
log file output

### ISSUE THREAD

**Issue by adoti** [asperellis/albatross#2]
_At the moment we just need to see what Albatross thinks it's doing, but once we go online we'll want to compare what we thought we were doing with what we actually did.  For now, the log should look like this:_

1. start time/date
2. start wallet - _see desired format below_
3. trade log
4. end time/date
5. end wallet

_**wallet format**_
wallet should print out something like this:

"GDAX:{
{BTC}:0
{ETH}:0
{LTC}:0

poloniex:
{BTC}:0
..."

key is to maintain the same order between wallets and to have the line breaks between exchanges.  i'll end up splitting these by the ":" so any version of something like that will work.

_**trade log**_
trade log should be in the following format w/ a line break after each log:
date/time, trade counter, asset, currency, market1, market2, asset amt sold/bought, currency spent, currency gained

for example:
"1/15/18 10:04 AM", 1, "LTC", "ETH", "poloniex", "bittrex", 0.52099311523, 0.0163452892, 0.01637623461

**_future_**
eventually we'll log the expected and actual results.  this would keep the same trade log format but would have an "actual" asset sold, curr received, curr spent, asset received to compare and make sure we're not losing money in the time it takes for trades to execute.

**Comment by asperellis** [comment]
Log updates added.
Wallet clean and csv ready trade logs added as well
