### ISSUE TITLE
LOT_SIZE error/MIN_ORDER_QTY

### ISSUE THREAD

**Issue by adoti** [asperellis/albatross#20]
We're erroring out on Binance because we don't check the min_trade qty before trade execution: there will be times where a trade looks good, we have the minimum amounts in our wallets to trade, but the available order book qtys will be lower than our min_trade.  Because (I assume) that MIN_TRADE is evaluated before limiting calculations are done, if the limiting calculation lowers the amt to trade lower than the MIN_TRADE, a LOT_SIZE error will trigger and halt execution.  Need to check our startAsset/startCurrency against MIN_TRADE one last time before trade execution and, if not > MIN_TRADE, abort trade.

**Comment by adoti** [comment]
similarly, we need to make sure the qty's we're sending to the exchange (particularly market2) have been truncated per the trading rules before being sent off to the exchange as trade commands.  that is, before, we were interested in the amt of BTC we were spending so we could adjust the paper wallet to see if our algorithm was profitable.  now, we're interested in sending an amount of ASSET to purchase on market2, but all of the calculations before that point look for an amount of BTC to spend on market2.  i think that once we perform limiting calculations and generate the amt of BTC to spend on market2 (aka startCurrency) and then divide the BTC to spend by the going price, we're adding decimal places and ruining the previous precision calculation.

This is just a hunch due to the below screenshot: other "LOT_SIZE" errors seemed to be because we were looking to transact < .001 BTC (the minimum trade size in BTC on Binance), but this one seems to meet that minimum quantity but still error out with the "LOT_SIZE" error.
![image](https://user-images.githubusercontent.com/34661902/39129467-8d24866e-46d8-11e8-8183-0218d1c1d6e2.png)

**Comment by adoti** [comment]
for comparison: a "LOT_SIZE" error that seems to be because we're trying to transact < 0.001 BTC
![image](https://user-images.githubusercontent.com/34661902/39129646-00ff3ade-46d9-11e8-9c2a-ea245fb110d7.png)

**Comment by adoti** [comment]
idea: instead of outputting the amount of BTC to transact, getLimits should output the amount of asset to sell on market1 and the amount of asset to buy on m2.  then we don't have to convert anything or truncate it at execution.  would change the flow a bit from the paper version but idk, something to consider.

THEN, we truncate each asset buy/sell by the individual exchange's trading precision rule so we don't get errors back.

(to get the amt of asset you want to buy on market 2, just don't multiply whatever = startCurrency by trade.market2.ask.  then startCurrency actually = buyAsset and startAsset = sellAsset.

**Comment by asperellis** [comment]
Complete
