### ISSUE TITLE
Truncate decimals to x places

### ISSUE THREAD

**Issue by adoti** [asperellis/albatross#8]
new getLimits modification will need a truncate function to work because Binance sucks dick.  should look like truncate(floating point number, number of digits)

**Comment by asperellis** [comment]
added to trader.js - truncateAmount method - for now. not sure where to place. May end up putting inside the new limits func.

truncate
params: num - the number and decimals: the number of decimal points

returns truncated decimal number

ex: truncate(1.23456, 2) returns 1.23

if you dont pass in a valid number => return false
if you pass in a number with less decimals than given decimals OR if there is no decimal OR if decimals <=0 just return the number
all other cases should work.
